baseURL: "https://blog.juanrloaiza.com/"
languageCode: es-co
title: Juan R. Loaiza's Blog
defaultContentLanguage: es

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - $
              - $
            - - \(
              - \)
        enable: true

languages:
  es:
    contentDir: content/es
  en:
    contentDir: content/en

menu:
  main:
    - name: Inicio
      pageRef: /
      weight: 1
    - name: Archivo
      pageRef: /posts
      weight: 2

permalinks:
  posts: /posts/:year/:month/:title/

params:
  byline: "Filósofo y docente"
  math: true
